module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {},
    colors: {
      white: "#FCFCFE",
      light: "#F9F8FD",
      dark: "#2E2F34",
      lightdark: "#808186",
      gray: "#A4A2A5",
      green: "#0ebb00",
      light_green: "#56ff48",
      pink: "#F6BDD2",
      purple: "#7E43B1",
      red: "#F75864",
      matt_green: "#63C8AA",
      deep_blue: "#01175A",
    },
    fontSize: {
      xxs: ".65rem",
      xs: ".75rem",
      sm: ".875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
    },
  },
  plugins: [],
};
